version: '3.7'

services:
  koji-builder:
    image: "yufenkuo/builder-launcher"
    deploy:
      replicas: 1
    depends_on:
      - koji-hub
    volumes:
      - type: bind
        source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
      - type: bind
        source: '/koji/mock'
        target: '/koji/mock'
    environment:
      HOST: '${HOST:-hqswarm3-node1}' 
      GIT_HOST_IP: '${GIT_HOST_IP}' 
      MIRROR_HOST_IP: '${MIRROR_HOST_IP}' 
      EXTRA_DOCKER_RUN_OPTIONS: '--add-host=gitcentos.mvista.com:$GIT_HOST_IP --add-host=centos7mirror.mvista.com:$MIRROR_HOST_IP'
    
