version: '3.7'

services:
  nginx:
    image: "nginx:stable-alpine"
    deploy:
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: '/mirrors'
        target: '/mirrors'
      - type: bind
        source: '/tmp/koji-setup/default.conf'
        target: '/etc/nginx/conf.d/default.conf'
        read_only: true
  koji-db:
    image: "${IMAGE_KOJI_DB:-postgres:9.4}"
    deploy:
      replicas: 1
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: '/db/postgres/data'
        target: '/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: 'koji' 
      POSTGRES_USER: 'koji'
      POSTGRES_PASSWORD: 'mypassword'
  koji-hub:
    image: "${IMAGE_KOJI_HUB:-yufenkuo/koji-hub}"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    depends_on:
      - koji-db
    ports:
      - "9080:80"
      - "443:443"
    extra_hosts:
      - "gitcentos.mvista.com:$GIT_HOST_IP"
      - "centos7mirror.mvista.com:$MIRROR_HOST_IP"
    volumes:
      - type: bind
        source: '${KOJI_OUTPUT:-/srv}'
        target: '/srv'
      - type: bind
        source: '${KOJI_CONFIG:-/config}'
        target: '/config'
      - type: bind
        source: '/koji/saved/etc/pki/koji'
        target: '/root/saved/etc/pki/koji'
    environment:
      GIT_HOST_IP: '${GIT_HOST_IP}'
      MIRROR_HOST_IP: '${MIRROR_HOST_IP}'
      KOJI_DB: '${HOST:-hqswarm3-node1}'
      KOJI_HUB_IP: '${HOST:-hqswarm3-node1}'
      GIT_BRANCH: 'koji-1.18-updates' 
      KOJI_PACKAGER: '${KOJI_PACKAGER}'
      KOJI_VENDOR: '${KOJI_VENDOR}'
      KOJI_OUTPUT: '${KOJI_OUTPUT}'
      
