version: '3.7'

services:
  git-server:
    image: "yufenkuo/git-server"
    deploy:
      replicas: 1
    ports:
      - "2222:22"
      - "9418:9418"
    volumes:
      - type: bind
        source: '~/git-server/keys'
        target: '/git-server/keys'
      - type: bind
        source: '/git-server/repos'
        target: '/git-server/repos'


